version: '2'
services:
  mogilefs_mysql:
    image: 'mysql'
    container_name: mogilefs_mysql
    volumes:
      - mogilefs_mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mogilefs
      - MYSQL_USER=mogile
      - MYSQL_PASSWORD=123456
    networks:
      mogilefs:
        aliases:
          - mysqlhost
  store1:
    image: mogilefs
    container_name: store1
    command: "mogstored"
    volumes:
      - mogilefs_storedata1:/mogdata/
      - ./etc/mogilefs/:/etc/mogilefs/
    networks: 
      mogilefs:
        aliases:
          - store1
  store2:
    image: mogilefs
    container_name: store2
    command: "mogstored"
    volumes:
      - mogilefs_storedata2:/mogdata/
      - ./etc/mogilefs/:/etc/mogilefs/
    networks: 
      mogilefs:
        aliases:
          - store2
  store3:
    image: mogilefs
    container_name: store3
    command: "mogstored"
    volumes:
      - mogilefs_storedata3:/mogdata/
      - ./etc/mogilefs/:/etc/mogilefs/
    networks: 
      mogilefs:
        aliases:
          - store3
  tracker1:
    image: mogilefs
    container_name: tracker1
    depends_on: 
      - mogilefs_mysql
    environment:
      - TRACKER=1
    user: mogile 
    command: 'mogilefsd'
    volumes:
      - ./etc/mogilefs/:/etc/mogilefs/
    networks: 
      mogilefs:
        aliases:
          - tracker1
  tracker2:
    image: mogilefs
    container_name: tracker2
    environment:
      - TRACKER=1
    depends_on: 
      - mogilefs_mysql
    user: mogile 
    command: 'mogilefsd'
    volumes:
      - ./etc/mogilefs/:/etc/mogilefs/
    networks: 
      mogilefs:
        aliases:
          - tracker2
networks:
  mogilefs:
    driver: bridge
volumes:
  mogilefs_mysqldata:
  mogilefs_storedata1:
  mogilefs_storedata2:
  mogilefs_storedata3:
